- name: Installation du serveur web
  hosts: apache
  remote_user: defaults
  tasks:
    - name: install apache
      apt: name=apache2
    - name: install  php
      apt: name=php
    - name: Start Apache
      service:
        - name: apache2
        - state: started


- name: Installation du serveur web
  hosts: nginx
  remote_user: defaults
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest 
    - name: Start nginx
      service:
        - name: nginx
        - state: started
